export const STORAGE_KEYS = {
  BEST_SCORE: '@ns:best_score',
  SCORE_HISTORY: '@ns:score_history',
  RANKING_ALL: '@ns:ranking_all',
  RANKING_WEEKLY: '@ns:ranking_weekly',
  RANKING_DAILY: '@ns:ranking_daily',
  TOTAL_GAMES: '@ns:total_games',
  TOTAL_BLOCKS_CLEARED: '@ns:total_blocks',
  TOTAL_PLAYTIME_MS: '@ns:total_playtime',
  HIGHEST_COMBO: '@ns:highest_combo',
  PERFECT_CLEARS: '@ns:perfect_clears',
  FEVER_ACTIVATIONS: '@ns:fever_activations',
  SPECIAL_BLOCKS_USED: '@ns:special_blocks_used',
  COINS: '@ns:coins',
  UNLOCKED_THEMES: '@ns:unlocked_themes',
  CURRENT_THEME: '@ns:current_theme',
  ACHIEVEMENTS: '@ns:achievements',
  DAILY_CHALLENGES: '@ns:daily_challenges',
  DAILY_STREAK: '@ns:daily_streak',
  SETTINGS: '@ns:settings',
  AD_REMOVED: '@ns:ad_removed',
  CONTINUE_TOKENS: '@ns:continue_tokens',
  GAME_COUNT: '@ns:game_count',
  TOTAL_SCORE: '@ns:total_score',
  TUTORIAL_SEEN: '@ns:tutorial_seen',
  WEEKLY_CHALLENGE: '@ns:weekly_challenge',
} as const;
